name: Bug Report Notification

on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true

jobs:
  generate-bug-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repositories
      uses: actions/checkout@v3
    
   - name: Collect Bug Reports
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      run: |
        python <<EOF
        import os
        import requests
        from github import Github

        # Get current repository
        current_repo = os.environ['GITHUB_REPOSITORY']

        # Initialize GitHub client
        g = Github(os.environ['GITHUB_TOKEN'])

        # Collect bugs for current repository
        repo = g.get_repo(current_repo)
        bugs = repo.get_issues(state='open', labels=['bug'])

        # Create slack payload
        PAYLOAD=$(cat <<EOF
        {
          "text": "New Bug Report in *${GITHUB_REPOSITORY}*",
          "attachments": [
            {
              "color": "#FF0000",
              "title": "${GITHUB_EVENT_PATH}",
              "title_link": "${GITHUB_EVENT_PATH}",
              "fields": [
                {
                  "title": "Title",
                  "value": "${{ github.event.issue.title }}",
                  "short": false
                },
                {
                  "title": "Reporter",
                  "value": "${{ github.event.issue.user.login }}",
                  "short": true
                }
              ]
            }
          ]
        }
        EOF
        )
        
        curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" $SLACK_WEBHOOK
