name: Set "Opened On" in Project

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'  # Run every 15 minutes

permissions:
  contents: read
  repository-projects: write
  organization-projects: write

jobs:
  set-opened-on:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.DATE_AUTOMATION }}
      PROJECT_ID: "PVT_kwDOA9MHEM4AgKVv"
      FIELD_ID: "PVTF_lADOA9MHEM4AgKVvzg4bxWU"
    steps:
      - name: Process Project Items
        run: |
          set +e  # Don't exit on errors, handle them per-item
          
          if [ -z "$GH_TOKEN" ]; then
            echo "Error: GH_TOKEN (DATE_AUTOMATION secret) is not set" >&2
            exit 1
          fi

          # Fetch all items from the project with pagination
          echo "Fetching items from project..."
          ALL_ITEMS=""
          CURSOR=""
          PAGE_NUM=1
          
          while true; do
            echo "Fetching page $PAGE_NUM..."
            
            if [ -z "$CURSOR" ]; then
              PROJECT_DATA=$(gh api graphql -f query='
              query($projectId:ID!){
                node(id:$projectId){
                  ... on ProjectV2 {
                    items(first:100){
                      nodes{
                        id
                        fieldValueByName(name:"Opened On"){
                          ... on ProjectV2ItemFieldDateValue {
                            date
                          }
                        }
                        content{
                          ... on Issue {
                            id
                            number
                            createdAt
                          }
                        }
                      }
                      pageInfo{
                        hasNextPage
                        endCursor
                      }
                    }
                  }
                }
              }' -F projectId="$PROJECT_ID" 2>&1)
            else
              PROJECT_DATA=$(gh api graphql -f query='
              query($projectId:ID!, $cursor:String!){
                node(id:$projectId){
                  ... on ProjectV2 {
                    items(first:100, after:$cursor){
                      nodes{
                        id
                        fieldValueByName(name:"Opened On"){
                          ... on ProjectV2ItemFieldDateValue {
                            date
                          }
                        }
                        content{
                          ... on Issue {
                            id
                            number
                            createdAt
                          }
                        }
                      }
                      pageInfo{
                        hasNextPage
                        endCursor
                      }
                    }
                  }
                }
              }' -F projectId="$PROJECT_ID" -F cursor="$CURSOR" 2>&1)
            fi

            # Check for errors fetching project data
            if [ $? -ne 0 ] || ! echo "$PROJECT_DATA" | jq -e '.data.node.items' > /dev/null 2>&1; then
              echo "Error: Failed to fetch project data on page $PAGE_NUM" >&2
              echo "Response: $PROJECT_DATA" >&2
              exit 1
            fi

            # Extract items from this page
            PAGE_ITEMS=$(echo "$PROJECT_DATA" | jq -c '.data.node.items.nodes[]')
            
            if [ -n "$PAGE_ITEMS" ]; then
              if [ -z "$ALL_ITEMS" ]; then
                ALL_ITEMS="$PAGE_ITEMS"
              else
                ALL_ITEMS="$ALL_ITEMS"$'\n'"$PAGE_ITEMS"
              fi
            fi

            # Check if there are more pages
            HAS_NEXT_PAGE=$(echo "$PROJECT_DATA" | jq -r '.data.node.items.pageInfo.hasNextPage')
            
            if [ "$HAS_NEXT_PAGE" = "true" ]; then
              CURSOR=$(echo "$PROJECT_DATA" | jq -r '.data.node.items.pageInfo.endCursor')
              PAGE_NUM=$((PAGE_NUM + 1))
            else
              break
            fi
          done
          
          echo "Fetched $PAGE_NUM page(s) of items"

          # Extract items that need processing (issues without "Opened On" date)
          ITEMS_TO_PROCESS=$(echo "$ALL_ITEMS" | jq -c 'select(.content.id != null and (.fieldValueByName.date == null or .fieldValueByName.date == ""))')
          
          if [ -z "$ITEMS_TO_PROCESS" ]; then
            echo "No items need processing - all issues have 'Opened On' date set"
            exit 0
          fi

          TOTAL_COUNT=$(echo "$ITEMS_TO_PROCESS" | wc -l | tr -d ' ')
          echo "Found $TOTAL_COUNT item(s) to process"
          echo ""

          SUCCESS_COUNT=0
          ERROR_COUNT=0

          # Process each item (use process substitution to avoid subshell)
          while IFS= read -r item; do
            ITEM_ID=$(echo "$item" | jq -r '.id')
            ISSUE_NUMBER=$(echo "$item" | jq -r '.content.number')
            ISSUE_CREATED=$(echo "$item" | jq -r '.content.createdAt')

            # Validate extracted values before processing
            if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ] || \
               [ -z "$ISSUE_NUMBER" ] || [ "$ISSUE_NUMBER" = "null" ] || \
               [ -z "$ISSUE_CREATED" ] || [ "$ISSUE_CREATED" = "null" ]; then
              echo "✗ Skipping item due to missing required data (ITEM_ID='$ITEM_ID', ISSUE_NUMBER='$ISSUE_NUMBER', ISSUE_CREATED='$ISSUE_CREATED')" >&2
              ERROR_COUNT=$((ERROR_COUNT + 1))
              echo ""
              continue
            fi

            OPENED_DATE="${ISSUE_CREATED%%T*}"
            echo "Processing issue #$ISSUE_NUMBER..."

            # Set the "Opened On" field value
            UPDATE_RESP=$(gh api graphql -f query='
            mutation($projectId:ID!, $itemId:ID!, $fieldId:ID!, $date:Date!){
              updateProjectV2ItemFieldValue(input:{
                projectId:$projectId,
                itemId:$itemId,
                fieldId:$fieldId,
                value:{ date:$date }
              }){
                projectV2Item{ id }
              }
            }' \
            -F projectId="$PROJECT_ID" \
            -F itemId="$ITEM_ID" \
            -F fieldId="$FIELD_ID" \
            -F date="$OPENED_DATE" 2>&1)

            if [ $? -eq 0 ] && echo "$UPDATE_RESP" | jq -e '.data.updateProjectV2ItemFieldValue.projectV2Item.id' > /dev/null 2>&1; then
              echo "✓ Successfully set 'Opened On' to $OPENED_DATE for issue #$ISSUE_NUMBER"
              SUCCESS_COUNT=$((SUCCESS_COUNT + 1))
            else
              echo "✗ Error setting 'Opened On' for issue #$ISSUE_NUMBER" >&2
              
              # Try to extract error details
              if echo "$UPDATE_RESP" | jq -e '.errors' > /dev/null 2>&1; then
                echo "  Error details:" >&2
                echo "$UPDATE_RESP" | jq -r '.errors[] | "  - \(.message)"' >&2
              else
                echo "  Response: $UPDATE_RESP" >&2
              fi
              
              ERROR_COUNT=$((ERROR_COUNT + 1))
            fi
            echo ""
          done < <(echo "$ITEMS_TO_PROCESS")

          echo "Processing complete: $SUCCESS_COUNT succeeded, $ERROR_COUNT failed"
          
          # Exit with error if all items failed
          if [ "$ERROR_COUNT" -gt 0 ] && [ "$SUCCESS_COUNT" -eq 0 ]; then
            echo "Error: All items failed to process" >&2
            exit 1
          fi
          
          exit 0
